# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('bid', models.FloatField(verbose_name='Bid')),
                ('bid_type', models.CharField(max_length=3, verbose_name='bid type')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(max_length=80)),
                ('bid_types', models.CharField(choices=[('cpm', 'CPM'), ('cpv', 'CPV'), ('cpa', 'CPA'), ('cpi', 'CPI'), ('cpc', 'CPC')], default='cpc', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Channel', verbose_name='Cannel'),
        ),
    ]
