# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170726_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='bid_type',
            field=models.CharField(choices=[('cpv', 'CPV'), ('cpi', 'CPI'), ('cpa', 'CPA'), ('cpm', 'CPM'), ('cpc', 'CPC')], default='cpc', max_length=3, verbose_name='bid type'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bid_types',
            field=models.CharField(choices=[('cpv', 'CPV'), ('cpi', 'CPI'), ('cpa', 'CPA'), ('cpm', 'CPM'), ('cpc', 'CPC')], default='cpc', max_length=3),
        ),
    ]
