# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170727_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='bid_type',
            field=models.CharField(choices=[('cpm', 'CPM'), ('cpi', 'CPI'), ('cpa', 'CPA'), ('cpc', 'CPC'), ('cpv', 'CPV')], max_length=3, verbose_name='bid type'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bid_types',
            field=models.CharField(choices=[('cpm', 'CPM'), ('cpi', 'CPI'), ('cpa', 'CPA'), ('cpc', 'CPC'), ('cpv', 'CPV')], default='cpc', max_length=3),
        ),
    ]
