# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170728_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='bid_type',
            field=models.CharField(choices=[('cpv', 'CPV'), ('cpc', 'CPC'), ('cpa', 'CPA'), ('cpi', 'CPI'), ('cpm', 'CPM')], max_length=3, verbose_name='bid type'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bid_types',
            field=models.CharField(choices=[('cpv', 'CPV'), ('cpc', 'CPC'), ('cpa', 'CPA'), ('cpi', 'CPI'), ('cpm', 'CPM')], default='cpc', max_length=3),
        ),
    ]
