# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170728_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='bid_type',
            field=models.CharField(choices=[('cpm', 'CPM'), ('cpa', 'CPA'), ('cpc', 'CPC'), ('cpv', 'CPV'), ('cpi', 'CPI')], max_length=3, verbose_name='bid type'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(default=main.models.Channel, on_delete=django.db.models.deletion.CASCADE, related_name='name_channel', to='main.Channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bid_types',
            field=models.CharField(choices=[('cpm', 'CPM'), ('cpa', 'CPA'), ('cpc', 'CPC'), ('cpv', 'CPV'), ('cpi', 'CPI')], default='cpc', max_length=3),
        ),
    ]
