# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170728_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='bid_type',
            field=models.CharField(choices=[('cpm', 'CPM'), ('cpa', 'CPA'), ('cpc', 'CPC'), ('cpi', 'CPI'), ('cpv', 'CPV')], default='cpc', max_length=3, verbose_name='bid type'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bid_types',
            field=models.CharField(choices=[('cpm', 'CPM'), ('cpa', 'CPA'), ('cpc', 'CPC'), ('cpi', 'CPI'), ('cpv', 'CPV')], default='cpc', max_length=3),
        ),
    ]
