# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170729_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='available',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='bid_type',
            field=models.CharField(choices=[('cpi', 'CPI'), ('cpa', 'CPA'), ('cpv', 'CPV'), ('cpm', 'CPM'), ('cpc', 'CPC')], default='cpc', max_length=3, verbose_name='bid type'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bid_types',
            field=models.CharField(choices=[('cpi', 'CPI'), ('cpa', 'CPA'), ('cpv', 'CPV'), ('cpm', 'CPM'), ('cpc', 'CPC')], default='cpc', max_length=3),
        ),
    ]
